groupup/groupup/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "accounts"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register/", views.register, name = "register"),
    path("login/", views.homepage, name = "index"),
    path("groups/", views.all_groups, name="groups"),
    path("groups/<int:pk>/", views.group_site, name="group_site"),
    path("groups/<int:pk>/remove-member/<int:user_id>", views.remove_group_member),
    path("groups/<int:pk>/matches", views.group_matches, name="group_matches"),
    path("groups/create/", views.UserGroupCreateView.as_view(), name="group_create"),
    path("profile/invites", views.show_invites, name="invites"),
    path("profile/acceptinvite/<int:pk>", views.accept_invite, name="accept_invite"),
    path("profile/declineinvite/<int:pk>", views.decline_invite, name="decline_invite"),
]

urlpatterns += staticfiles_urlpatterns()

groupup/groupup/groupup_admin/urls.py
from django.urls import path
from . import views

app_name = "group_admin"

urlpatterns = [
    path('sendmatchrequest/<int:pk>', views.send_match_request, name='send_match'),
    path('viewmatchrequests/<int:pk>', views.view_match_requests, name='view_match'),
    path('handle_requests/<int:pk>', views.handle_match_request, name='handle_request'),
    path('groups/<int:pk>/add_date', views.add_date, name='add_date'),
    path('groups/<int:pk>/remove_date', views.remove_date, name='remove_date'),
    path('groups/<int:pk>/set_have_met', views.have_met, name='set_met'),
    path('groups/review/<int:pk>', views.write_review, name='write_review'),
    path('groups/<int:pk>/delete', views.delete_group, name="delete_group")
] 

groupup/groupup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('', include('groupup.accounts.urls'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', include('groupup.groupup_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupup/groupup/accounts/forms.py
import datetime
import dateutil
from django import forms
from dateutil.relativedelta import relativedelta
from groupup.accounts.models import UserGroup, GroupUpUser
from .models import Interest
from .widgets import DatePickerInput

class InterestsWidget(forms.SelectMultiple):
    template_name="widgets/interests_widget.html"


def validate_birthday(value: datetime.date):
    if ((value + relativedelta(years=18)) >= datetime.date.today()):
        raise forms.ValidationError("You are too young.")

class RegisterForm(forms.Form):
    """Form for creating a new groupupuser"""
    
    username = forms.CharField(label="username", max_length=100)
    password = forms.CharField(label="password", widget=forms.PasswordInput)
    profile_pic = forms.ImageField(label="profile_pic")
    interests = forms.ModelMultipleChoiceField(
                                    label="interests",
                                    queryset=Interest.objects.all(),
                                    widget=InterestsWidget)
    birthday = forms.DateField(label="dateofbirth", widget=DatePickerInput, validators=[validate_birthday])

class GroupCreateForm(forms.ModelForm):
    """A form for creating new groups."""
    interests = forms.ModelMultipleChoiceField(
                                    label="Interests",
                                    queryset=Interest.objects.all(),
                                    widget=InterestsWidget)

    class Meta:
        model = UserGroup
        fields = ["name", "description", "group_pic", "admin_contact"]

    def save(self, owner: GroupUpUser) -> UserGroup:
        """
        Creates a new instance of GroupUpUser and saves the result.
        """
        self.instance.group_admin = owner
        self.instance.admin_contact = self.cleaned_data['admin_contact']
        returnValue = super().save(commit=True)
        self.instance.members.add(owner)
        for interest in self.cleaned_data['interests']:
            self.instance.interests.add(interest.id)
        return returnValue

groupup/groupup/accounts/views.py
from numbers import Number
from posixpath import split
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic.edit import FormView
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .models import Interest, UserGroup
from django.contrib.auth.decorators import login_required
from django.forms import ValidationError
from .models import GroupUpUser, UserGroup
from .forms import RegisterForm, GroupCreateForm
from groupup.groupup_admin.forms import InviteUserForm, AddAvailableDateForm, RemoveDate
from django.contrib import messages
from django.contrib.auth.models import User
from groupup.groupup_admin.models import Invite
from django.db.models.functions import Lower
from django.contrib.auth import authenticate, login

def homepage(request):
    """Renders the homepage for the user."""
    
    try:
        groups = request.user.groupupuser.get_groups()
        context = {"groups": groups}
        return render(request, "accounts/home.html", context)

    except AttributeError:
        return redirect(reverse("login"))

class UserGroupCreateView(LoginRequiredMixin, FormView):
    """View for creating new groups."""

    http_method_names = ['get', 'post']
    form_class = GroupCreateForm
    template_name = "accounts/group_creation.html"

    def form_valid(self, form: GroupCreateForm):
        obj = form.save(self.request.user.groupupuser)
        self.success_url = obj.get_absolute_url()
        return super().form_valid(form)

def register(request):
    """View for handling new groupupusers
    
    Checks if request method is POST. If the form is valid it creats a new user and groupupuser.
    If request method i GET it returns a empty form.
    """

    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            if len(User.objects.filter(username=data.get("username"))) != 0:
                raise ValidationError(
                    ("Username already taken"),
                    code = "username_taken"
                )
            
            user = User.objects.create_user(username=data.get("username"), password=data.get("password"))
            user.save()
            groupupuser = GroupUpUser(user=user, profile_pic=data.get("profile_pic"),birthday=data.get("birthday"))
            groupupuser.save()
            for interest in list(data.get("interests")):
                groupupuser.interests.add(interest.id)
            groupupuser.save()

            authenticate(username=form.cleaned_data['username'],
                password=form.cleaned_data['password'])
            login(request, user)
            return HttpResponseRedirect(reverse('accounts:homepage'))

    else:
        form = RegisterForm()
    return render(request, 'registration/registerForm.html', {'form': form})


@login_required
def all_groups(request):
    """Renders a page with all groups."""
    
    allInterests = list(Interest.objects.all().order_by(Lower('name'), 'pk'))
    filteredInterests = request.GET.get("interests")

    groups = list(UserGroup.objects.all().order_by(Lower('name'), 'pk'))
    result = []
    if filteredInterests is None or len(filteredInterests) == 0:
        result = groups
    else:
        for group in groups:
            if set([int(x) for x in filteredInterests.split(',')]).issubset(set([int(x.pk) for x in group.interests.all()])):
                result.append(group)
    return render(request, "accounts/all_groups.html", {"groups": result, "interests": allInterests})

@login_required
def group_site(request, pk):
    """Renders the group site of the group with primary key pk."""

    group = UserGroup.objects.get(pk=pk)

    request.session["pp_groupbrowsing"] = True
    request.session["group_pk"] = pk

    # form handling
    if request.method == "POST" and "invite_user" in request.POST:
        invite_form = InviteUserForm(request.POST)
        if invite_form.is_valid():
            user = None
            try:
                user = GroupUpUser.objects.get(user=User.objects.get(username=invite_form.cleaned_data.get("username")))
                if user.is_member_of_group(group):
                    messages.warning(request, "User already a member")
                elif user.has_pending_invite(group):
                    messages.warning(request, "Already invited user")
                else:
                    invite = Invite.objects.create(group=group, receiver=user)
                    invite.save()
                    messages.success(request, "Successfully invited the user!")

            except:
                messages.warning(request, "User does not exist.")
            invite_form = InviteUserForm()
            return HttpResponseRedirect(request.path)
    else:
        invite_form = InviteUserForm()
    add_date = AddAvailableDateForm()
    remove_date = RemoveDate(group)

    context = {
        "group": group,
        "invite_form": invite_form,
        "add_date": add_date,
        "remove_date": remove_date,
    }
    #context = {"group": group}
    return render(request, "accounts/group_site.html", context)

@login_required
def remove_group_member(request, pk, user_id):
    group = UserGroup.objects.get(pk=pk)
    if group not in request.user.groupupuser.get_groups_where_admin():
        return HttpResponse('Unauthorized', status=401)
    
    user_to_delete = User.objects.get(pk=user_id)
    if user_to_delete == request.user.groupupuser:
        return HttpResponse("Can not remove one self from the group.")
        
    group.remove_member(user_to_delete.groupupuser)
    group.save()


@login_required
def group_matches(request, pk):
    """Renders a list of groups in which the group with primary key pk has a confirmed match with."""
    
    group = UserGroup.objects.get(pk=pk)
    if group not in request.user.groupupuser.get_groups():
        return Http404
    
    confirmed_groups = group.get_confirmed_groups()
    context = {
        "confirmed_groups": confirmed_groups,
        "usergroup": group
    }

    return render(request, "accounts/group_matches.html", context)


@login_required
def show_invites(request):
    user = request.user.groupupuser
    pending_invites = user.get_pending_invitations()

    context = {"pending_invites": pending_invites}

    return render(request, "accounts/show_invites.html", context)


@login_required
def accept_invite(request, pk):
    group = UserGroup.objects.get(pk=pk)
    user = request.user.groupupuser
    
    if user in group.get_members():
        raise Http404
    
    invitation = Invite.objects.get(group=group, receiver=user, status="pending")
    invitation.status = "confirmed"
    invitation.save()
    group.members.add(user)
    group.save()

    return HttpResponseRedirect("/profile/invites")


@login_required
def decline_invite(request, pk):
    group = UserGroup.objects.get(pk=pk)
    user = request.user.groupupuser
    
    if user in group.get_members():
        raise Http404
    
    invitation = Invite.objects.get(group=group, receiver=user, status="pending")
    invitation.status = "rejected"
    invitation.save()

    return HttpResponseRedirect("/profile/invites")

groupup/groupup/accounts/templates/accounts/all_groups.html
{% extends 'accounts/base.html' %}

{% block content %}
<style>
  .checkbox-dropdown {
    width: 200px;
    border: 1px solid #aaa;
    padding: 10px;
    position: relative;
    user-select: none;
  }

  /* Display CSS arrow to the right of the dropdown text */
  .checkbox-dropdown:after {
    content: '';
    height: 0;
    position: absolute;
    width: 0;
    border: 6px solid transparent;
    border-top-color: #000;
    top: 50%;
    right: 10px;
    margin-top: -3px;
  }

  /* Reverse the CSS arrow when the dropdown is active */
  .checkbox-dropdown.is-active:after {
    border-bottom-color: #000;
    border-top-color: #fff;
    margin-top: -9px;
  }

  .checkbox-dropdown-list {
    list-style: none;
    margin: 0;
    padding: 0;
    position: absolute;
    top: 100%;
    /* align the dropdown right below the dropdown text */
    border: inherit;
    border-top: none;
    left: -1px;
    /* align the dropdown to the left */
    right: -1px;
    /* align the dropdown to the right */
    opacity: 0;
    /* hide the dropdown */

    transition: opacity 0.4s ease-in-out;
    max-height: 400px;
    overflow: scroll;
    overflow-x: hidden;
    pointer-events: none;
    /* avoid mouse click events inside the dropdown */
  }

  .is-active .checkbox-dropdown-list {
    opacity: 1;
    z-index: 100;
    /* display the dropdown */
    pointer-events: auto;
    /* make sure that the user still can select checkboxes */
  }

  .checkbox-dropdown-list li label {
    display: block;
    border-bottom: 1px solid silver;
    padding: 10px;
    transition: all 0.2s ease-out;
    background: #fff;
  }

  .checkbox-dropdown-list li label:hover {
    background-color: #555;
    color: white;
  }

  .dismiss-overlay.is-active {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    height: 100%;
    width: 100%;
    z-index: 1;
  }
</style>

<div class="container mb-4">
  <h1 style="text-align: center; margin-top: 10px;">All Groups</h1>
  
  <div class="row mb-4">
    <div class="col-md-1 col-xl-1">
    </div>
    <div class="col-md-10 col-xl-10" style="display: flex; flex-direction: row;">
      <div class="checkbox-dropdown">
        Filter on interest
        <ul class="checkbox-dropdown-list">
          {% for interest in interests %}
          <li>
            <label>
              <input type="checkbox" value="{{interest.pk}}" name="{{interest.name}}" />{{ interest.name }}</label>
          </li>
          {% endfor %}
        </ul>
      </div>
      <a class="btn btn-success" href="{% url 'accounts:group_create' %}" style="margin-left: 20px;">+ Create new group</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1 col-xl-1"></div>
    <div class="col-md-10 col-xl-10">
      <div class="d-flex flex-wrap justify-content-around" style="gap: 10px;">
      {% for group in groups %}
        <div class="group-item">
          <a class="text-decoration-none" style="color: inherit;" href="{% block group_links %}{% url 'accounts:group_site' group.id %}{% endblock %}">
          <img class="group-pic-list" src="{{ MEDIA_URL }}{{ group.group_pic.url }}" alt="Group picture for {{ group.name }}">
          <h2>{{ group.name }}</h2>
          <p>{{ group.get_age_gap }}</p>
          <h3>Some Interests</h3>
          <ul class="list-group list-group-horizontal" style="background-color: lightgrey;">
            {% for interest in group.get_three_interests %}
            <li class="list-group-item flex-fill">{{ interest.name }}</li>
            {% endfor %}
          </ul>
          </a>
        </div>
      {% endfor %}
      </div>
    </div>
    <div class="col-md-1 col-xl-1"></div>
  </div>
</div>

<div class="dismiss-overlay"></div>

<script>
  const searchParams = new URLSearchParams(window.location.search);
  const originalCheckedItems = (searchParams.get("interests") ?? "")
    .split(",")
    .filter(x => x !== "");
  Array.from(document.querySelectorAll(".checkbox-dropdown-list input[type=checkbox]"))
    .forEach(i => i.checked = originalCheckedItems.indexOf(i.value) >= 0);

  const dismissOverlay = document.querySelector(".dismiss-overlay");
  dismissOverlay.addEventListener('click', e => {
    document.querySelector(".checkbox-dropdown").classList.remove("is-active");
    e.currentTarget.classList.remove("is-active");
  });

  document.querySelector(".checkbox-dropdown").addEventListener("click", e => {
    e.stopPropagation();
    e.currentTarget.classList.toggle("is-active");
    dismissOverlay.classList.toggle("is-active");
    const searchParams = new URLSearchParams(window.location.search);
    const checkedItems = Array.from(
      document.querySelectorAll(".checkbox-dropdown-list input[type=checkbox]"))
      .filter(x => x.checked)
    if (checkedItems.length === originalCheckedItems.length) {
      return;
    }
    searchParams.set(
      "interests",
      checkedItems.map(x => x.value).join(","));
    window.location.search = searchParams.toString();
  });
</script>
{% endblock %}

groupup/groupup/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {# Load the tag library #}
    {% load bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    
    {% load static %}
    
    {# Interests widget #}
    <link rel="stylesheet" type="text/css" href="{% static 'groupup/css/interests_widget.css' %}">
    <script src='{% static "groupup/js/interests_widget.js" %}'></script>

    <title>{% block title %}{% endblock%}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'groupup/css/filters.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'groupup/css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'groupup/img/favicon.ico' %}">
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% if user.is_authenticated %}
    <nav class="navbar sticky-top navbar-dark bg-dark">
      <div class="container" style="margin-left: 0cm; justify-content: left;" >
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" style="margin-left: 20px;">
          <span class="navbar-toggler-icon"> </span>
        </button>
        <a class="navbar-brand" href="/"> {% load static %} <img src="{% static "groupup/img/favicon.ico" %}" alt="groupuplogo" style="width: 50px; height: 35px; object-fit: scale-down; margin-left: 20px;"/>GroupUp</a>
        <a class="nav-link" href="{% url 'accounts:invites' %}">
          <img class="profile-pic" src="{{ MEDIA_URL }}{{ user.groupupuser.profile_pic.url }}" style="margin-left: 980px;">
        </a>
        </div>

        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header" style="padding-bottom: 0;">
            <h4 class="offcanvas-title" id="offcanvasNavbarLabel"> {% load static %} <img src="{% static "groupup/img/favicon.ico" %}" alt="groupuplogo" style="width: 50px; height: 35px; object-fit: scale-down; margin-left: 20px;"> GroupUp</h4>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <hr>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3" style="padding-left: 15px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/" style="color: black; font-size: 22px; margin-bottom: 10px;">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:groups' %}" style="color: black; font-size: 22px; margin-bottom: 10px;">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:invites' %}" style="color: black; font-size: 22px; margin-bottom: 10px;">Profile</a>
              </li>
              <li>
                <a class="btn btn-danger" href="{% url 'logout' %}" style="margin-top: 450px; padding: 10px 140px">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% else %}
     
      {% block login %}
      {% endblock %}
      {% block register %}
      {% endblock %}
    {% endif %}
    <footer class="bg-light text-center mt-auto">
      <div class="container p-4">
        <div class="row">
          <div class="col-md-1 col-xl-1"></div>
          <div class="col-md-10 col-xl-10">
            <h5 class="text-uppercase">About</h5>
            <p>
              This is our project in the course TDT4140 "Programvareutvikling". The project uses the django framework
              with bootstrap as our frontend framework. All source code is on the groups
              <a href="https://gitlab.stud.idi.ntnu.no/tdt4140-2022/landsby-2/gruppe_32/groupup">gitlab.</a>
            </p>
          </div>
          <div class="col-md-1 col-xl-1"></div>
        </div>
      </div>
    </footer>
  </body>
</html>

groupup/groupup/accounts/templates/accounts/group_site.html
{% extends 'accounts/base.html' %}
{% load bootstrap5 %}


{% block content %}
<style>
    #sidepanel {
        background-color: #006A6E;
        width: 500px;
        height: 500px;
        border-radius: 25px;
    }

    div.scroll {
        height: 380px;
        overflow-x: hidden;
        overflow-y: auto;
        text-align: left;
    }
</style>
<div id="main" class="box" style="display: flex; flex-direction: row;">
    <div id="info" class="container" style="margin: 2em; width: fit-content;">
        <img src="{{ MEDIA_URL }}{{ group.group_pic.url }}"
            style="width: 800px; height: 300px; object-fit: cover; border-radius: 1.5em;">
        <h1 style="margin-top: 20px;">{{ group.name }}</h1>
        <p style="margin-top: 20px; margin-bottom: 40px;">{{ group.description }}</p>
        <h5 style="margin-bottom: 20px;">Interests</h5>
        <ul style="list-style-type: none; padding: 0;">
            <div style="display:flex; flex-direction:row;">
                {% for interest in group.interests.all %}
                <li>
                    <div
                        style="border: 0.1em solid; border-radius: 1em; width: fit-content; padding: 5px; padding-left: 15px; padding-right: 15px; margin-right: 10px;;">
                        {{ interest.name }}
                    </div>

                </li>
                {% endfor %}
            </div>
        </ul>
        <h5 style="margin-top: 40px;">Available on:</h5>
        <p style="margin-bottom: 40px;">
            {% if group.connected_group.all %}
            {% for date in group.connected_group.all %}
            {{ date.date }}
            {% endfor %}
            {% else %}
            Sorry, this group has not specified any available dates.
            {% endif %}
        </p>
        {% if group in user.groupupuser.get_groups %}
        <a class="btn btn-outline-success" href="{% url 'accounts:group_matches' group.id %}">See matches for {{ group.name }}!</a>
        {% endif %}
        {% if group in user.groupupuser.get_groups_where_admin %}
        <p>
            <a class="btn btn-outline-success" style="margin-top:1em;"
                href="{% url 'group_admin:view_match' group.id %}">
                See match requests for {{ group.name }}
            </a>
        </p>
        {% endif %}
        {% if group.reviews.all %}
        <h5 style="margin-bottom: 10px">Reviews</h5>
        <ul style="list-style-type: none; margin: 0; padding: 0;">
            {% for review in group.get_reviews %}
            <li>
                <div
                    style="border: 0.1em solid black; margin-top: 0.5em; border-radius: .3em; display: flex; justify-content: space-between;">
                    <p style="margin: 0; padding: 1em;">{{ review.review }}</p>
                    <p style="margin: 0; padding: 1em; border-left: 0.1em solid black;">{{ review.date_published }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div id="sidepanel" class="container" style="margin: 2em; color: white">
        <div style="margin: 1em; width: fit-content;">
            <p>Age-gap: {{ group.get_age_gap }}</p>
            <p>Admin E-mail: {{ group.admin_contact }}</p>
            <h5>Group members</h3>
        </div>
        <div class="scroll">
            <ul class="list-group">
                {% for member in group.members.all %}
                <li class="list-group-item">
                    <form class="delete-form d-flex">
                        {% csrf_token %}
                        <a href="{% url 'accounts:invites' %}">
                            <img class="profile-pic" src="{{ MEDIA_URL }}{{ member.profile_pic.url }}">
                        </a>
                        <span class="align-self-center mx-3">{{ member.user.username }}</span>
                        {% if user.groupupuser == group.group_admin and member != user.groupupuser %}
                        <input type="hidden" name="user_id" class="delete-form-user-id" value="{{ member.user.pk }}">
                        <div class="d-flex flex-grow-1"></div>
                        <button type="submit" class="btn btn-danger" style="line-height: 0;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                class="bi bi-trash" viewBox="0 0 16 16">
                                <path
                                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                <path fill-rule="evenodd"
                                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                            </svg>
                        </button>
                        {% endif %}
                    </form>
                </li>
                {% endfor %}
            </ul>
            {% block invite_user %}
                {% if group in user.groupupuser.get_groups_where_admin %}
                    <h2>Invite users</h2>
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form invite_form %}
                        {% buttons %}
                            <button type="submit" name="invite_user" class="btn btn-primary">
                            Invite!
                            </button>
                        {% endbuttons %}
                    </form>
                {% endif %}
            {% endblock %}

        </div>
    </div>
</div>
{% block admin_content %}
{% if user.groupupuser.is_a_group_admin %}
<div class="container" style="margin: 0 2em 2em 2em;">
    {% if group in user.groupupuser.get_groups_where_admin %}
    <h2>Add or remove available dates</h2>
    <form action="{% url 'group_admin:add_date' group.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form add_date %}
        {% buttons %}
        <button type="submit" class="btn btn-primary admin-buttons">
            Add
        </button>
        {% endbuttons %}
        {{ add_date.non_field_errors }}
    </form>
    <form action="{% url 'group_admin:remove_date' group.id %}" method="post">
        {% csrf_token %}
        {{ remove_date }}
        {% buttons %}
        <button type="submit" class="btn btn-primary admin-buttons" style="margin: 1em 0;">
            Remove
        </button>
        {% endbuttons %}
    </form>
    <a href="{% url 'group_admin:delete_group' group.id %}" class="btn btn-danger">Delete Group</a>
    {% else %}
    <div style="display: flex; flex-direction: column; gap: 1rem;">
        {% if group.connected_group.all %}
        <h2>Wanna match?</h2>
        {% for usergroup in user.groupupuser.get_groups_where_admin %}
        {% if group not in usergroup.get_related_groups %}
        <div>
            <a class="btn btn-primary" href="{% url 'group_admin:send_match' usergroup.id %}"
                style="width: 40%; word-break; break-word;">
                Send match request on behalf of {{ usergroup.name }}
            </a>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}

        {% if group in user.groupupuser.confirmed_groups_where_admin %}
        <h2>Have you met this group?</h2>
        {% endif %}
        {% for usergroup in user.groupupuser.get_groups_where_admin %}
        {% if group in usergroup.get_confirmed_groups %}
        <div>
            <a href="{% url 'group_admin:set_met' usergroup.id %}" class="btn btn-primary" style="width: 40%;">
                {{ usergroup.name }} have met this group
            </a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endif %}

<script>
    const deleteForms = document.querySelectorAll(".delete-form");
    for (const form of deleteForms) {
        form.addEventListener("submit", async e => {
            e.preventDefault();
            console.log(e)
            const id = e.target.querySelector(".delete-form-user-id").value;
            await fetch(`/groups/{{ group.pk }}/remove-member/${id}`);
            e.target.parentNode.remove();
        });
    }
</script>
{% endblock %}
{% endblock %}