groupup/groupup/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "accounts"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register/", views.register, name = "register"),
    path("login/", views.homepage, name = "index"),
    path("groups/", views.all_groups, name="groups"),
    path("groups/<int:pk>/", views.group_site, name="group_site"),
    path("groups/<int:pk>/remove-member/<int:user_id>", views.remove_group_member),
    path("groups/<int:pk>/matches", views.group_matches, name="group_matches"),
    path("groups/create/", views.UserGroupCreateView.as_view(), name="group_create"),
    path("profile/invites", views.show_invites, name="invites"),
    path("profile/acceptinvite/<int:pk>", views.accept_invite, name="accept_invite"),
    path("profile/declineinvite/<int:pk>", views.decline_invite, name="decline_invite"),
]

urlpatterns += staticfiles_urlpatterns()

groupup/groupup/groupup_admin/urls.py
from django.urls import path
from . import views

app_name = "group_admin"

urlpatterns = [
    path('sendmatchrequest/<int:pk>', views.send_match_request, name='send_match'),
    path('viewmatchrequests/<int:pk>', views.view_match_requests, name='view_match'),
    path('handle_requests/<int:pk>', views.handle_match_request, name='handle_request'),
    path('groups/<int:pk>/add_date', views.add_date, name='add_date'),
    path('groups/<int:pk>/remove_date', views.remove_date, name='remove_date'),
    path('groups/<int:pk>/set_have_met', views.have_met, name='set_met'),
    path('groups/review/<int:pk>', views.write_review, name='write_review'),
    path('groups/<int:pk>/delete', views.delete_group, name="delete_group")
] 

groupup/groupup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('', include('groupup.accounts.urls'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', include('groupup.groupup_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupup/groupup/groupup_admin/models.py
from django.db import models
from django.core.validators import RegexValidator


class Matches(models.Model):
    """Represents a relation between two groups.
    
    Has a requestor, a receiver and a status that can be either rejected, pending (defualt)
    or confirmed. A match also has a "have_met" field that keeps track on wheter the two groups
    have met or not.
    """
    
    requestor = models.ForeignKey("accounts.UserGroup", on_delete=models.CASCADE, related_name='match_requestor')
    receiver = models.ForeignKey("accounts.UserGroup", on_delete=models.CASCADE, related_name='match_receiver')
    status = models.CharField(max_length=10, default="pending" ,validators=[RegexValidator(regex="(rejected|pending|confirmed)$",
                                message="Must be one of the following: rejected, pending or confirmed")])
    have_met = models.BooleanField(default=False)


    class Meta:
        db_table = "matches"

    def set_have_met(self):
        self.have_met = True

    def __str__(self):
        return "match_between_{0}_{1}".format(self.requestor.id, self.receiver.id)


class Invite(models.Model):
    """Small table representing a invite to a group."""

    group = models.ForeignKey("accounts.UserGroup", on_delete=models.CASCADE, related_name="group")
    receiver = models.ForeignKey("accounts.GroupUpUser", on_delete=models.CASCADE, related_name="receiver")
    status = models.CharField(max_length=10, default="pending" ,validators=[RegexValidator(regex="(rejected|pending|confirmed)$",
                                message="Must be one of the following: rejected, pending or confirmed")])


    def __str__(self):
        return "{0}_invite_{1}".format(self.group.name, self.receiver.user.username)

        
    class Meta:
        db_table = "invite"

groupup/groupup/groupup_admin/forms.py
from django import forms
from groupup.accounts.widgets import DatePickerInput
from datetime import date as dt


def validate_date(date):
    if date < dt.today():
        raise forms.ValidationError("%s is before today".format(date))

class AddAvailableDateForm(forms.Form):
    """  """
    date = forms.DateField(label='Date to add', widget=DatePickerInput, validators=[validate_date])

class RemoveDate(forms.Form):
    """  """
    date = forms.ModelChoiceField(label='Date to remove', queryset=None)
    
    def __init__(self, group, *args, **kwargs):
        super(RemoveDate, self).__init__(*args, **kwargs)
        self.fields["date"].queryset = group.connected_group.all()




class HandleRequestForm(forms.Form):
    """Form for handling a match request, uses radio buttons."""

    CHOICES = [('confirmed', 'Accept'), ('rejected', 'Decline')]
    status = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)


class InviteUserForm(forms.Form):
    """Form for inviting a user"""

    username = forms.CharField(max_length=30, label="Username")


class ReviewForm(forms.Form):
    """"Form for wiriting reviews"""
    
    review = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":30}), label="")
    
    

groupup/groupup/groupup_admin/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from groupup.accounts.models import UserGroup, DateAvailable, Interest, Reviews
from .models import Matches
from .forms import HandleRequestForm, AddAvailableDateForm, RemoveDate, ReviewForm
from django.contrib import messages

@login_required
def send_match_request(request, pk):
    """Sends a match requests based on the session cookie group_pk.
    
    Does a few checks, for instance, it checks that the admin in fact is matching
    on behalf of a group he is admin of. It also checks if there is already a relation
    between the two groups. If all checks pass, a new match request is created.
    """

    if "pp_groupbrowsing" in request.session:
        requestor_group = UserGroup.objects.get(pk=pk)
        receiver_group = UserGroup.objects.get(pk=request.session.get("group_pk"))
        # check if group is itself
        if requestor_group == receiver_group:
            del request.session["pp_groupbrowsing"]
            raise Http404
        # check if user is actually admin of requestor_group
        if requestor_group not in request.user.groupupuser.get_groups_where_admin():
            del request.session["pp_groupbrowsing"]
            raise Http404
        # check if theres already a relation between the groups
        if requestor_group.has_relation_with(receiver_group):
            del request.session["pp_groupbrowsing"]
            raise Http404
        
        # everything good, create match
        match = Matches(requestor=requestor_group, receiver=receiver_group)
        match.save()

        # give feedback
        messages.success(request, "Sent a match request!")
        del request.session["pp_groupbrowsing"]
        return redirect("/groups/{0}".format(receiver_group.id))
    else:
        raise Http404

@login_required
def view_match_requests(request, pk):
    """Returns a view with a list of all groups that has requested a match with the group with primary_key=pk."""

    if not request.user.groupupuser.is_a_group_admin():
        return redirect("/groups/{0}".format(pk))
    group = UserGroup.objects.get(pk=pk)
    # check if user is actually admin of requestor_group
    if group not in request.user.groupupuser.get_groups_where_admin():
        raise Http404
    request.session['pp_viewmatches'] = True
    request.session['group_pk'] = pk
    
    # get matches (and therefore groups) where the status is pending
    requesting_groups = []
    matches = group.get_matches(True)
    for match in matches:
        if match.status == 'pending':
            requesting_groups.append(match.requestor)
    context = {'requesting_groups': requesting_groups, 'groupname': group.name}
    return render(request, 'groupup_admin/match_requests.html', context)

@login_required
def handle_match_request(request, pk):
    """Handle a match request, e.g accept or decline.
    
    Creates a HandleRequestForm, and renders it. If the input is valid,
    the status will be set according to the POST-request.
    """

    if 'pp_viewmatches' in request.session:
        requesting_group = UserGroup.objects.get(pk=pk)
        receiving_group = UserGroup.objects.get(pk=request.session.get('group_pk'))
        if not request.user.groupupuser.is_admin_of(receiving_group):
            del request.session['pp_viewmatches']
            raise Http404
        if request.method == 'POST':
            form = HandleRequestForm(request.POST)
            if form.is_valid():
                status = form.cleaned_data['status']
                match = Matches.objects.get(requestor=requesting_group, receiver=receiving_group, have_met = False)
                match.status = status
                match.save()
                if status == "confirmed":
                    messages.success(request, "You have matched with {0}".format(requesting_group.name))
                else:
                    messages.success(request, "You declined {0}'s match request".format(requesting_group.name))
                return HttpResponseRedirect('/admin/viewmatchrequests/{0}'.format(receiving_group.id))
        else:
            form = HandleRequestForm()
        context = {'group': requesting_group, 'form': form}
        return render(request, 'groupup_admin/group_site_handle_request.html', context)

@login_required
def add_date(request, pk):
    """Handles adding a date the group is available.
    
    Checks if the date is already added and redirects back to site if it is.
    """
    
    if request.method == 'POST':
        add_date_form = AddAvailableDateForm(request.POST)
        if add_date_form.is_valid():
            group = UserGroup.objects.get(pk=pk)
            date = add_date_form.cleaned_data['date']
            if len(DateAvailable.objects.filter(group=group, date=date))!=0:
                return redirect("/groups/{0}".format(pk))
            date_available = DateAvailable(group=group, date=date)
            date_available.save()
            #return HttpResponseRedirect("/admin/groups/{0}".format(pk))
            return HttpResponseRedirect("/groups/{0}".format(pk))
        else:
            #return redirect("/admin/groups/{0}".format(pk))
            return redirect("/groups/{0}".format(pk))
    else:
        #return redirect("/admin/groups/{0}".format(pk))
        return redirect("/groups/{0}".format(pk))

@login_required
def remove_date(request, pk):
    """Handles the removal of a available date for a group."""

    if request.method == "POST":
        group = UserGroup.objects.get(pk=pk)
        remove_date_form = RemoveDate(group, request.POST)
        if remove_date_form.is_valid():
            group = UserGroup.objects.get(pk=pk)
            date = remove_date_form.cleaned_data['date']
            date.delete()
            #return HttpResponseRedirect("/admin/groups/{0}".format(pk))
            return HttpResponseRedirect("/groups/{0}".format(pk))
    else:
        #return redirect("/admin/groups/{0}".format(pk))
        return redirect("/groups/{0}".format(pk))

@login_required
def have_met(request, pk):
    users_group = UserGroup.objects.get(pk=pk)
    group = UserGroup.objects.get(pk=request.session.get("group_pk"))

    match = list(Matches.objects.filter(receiver=users_group, requestor=group, have_met=False)) + list(Matches.objects.filter(receiver=group, requestor=users_group, have_met=False))
    print(match)
    if len(match) == 0 or len(match) > 1:
        return redirect("/groups/{0}".format(pk))
    match = match[0]
    match.have_met = True
    match.save()
    return redirect("/admin/groups/review/{0}".format(request.session.get("group_pk")))
    
@login_required
def write_review(request, pk):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            group = UserGroup.objects.get(pk=pk)
            review = Reviews.objects.create(group=group, review=review_form.cleaned_data["review"])
            review.save()
            return HttpResponseRedirect("/groups/{0}".format(pk))
    else:
        form = ReviewForm()
        context = {'form': form}
        return render(request, "groupup_admin/review.html", context)


@login_required
def delete_group(request, pk):
    group = UserGroup.objects.get(pk=pk)
    if request.method == "POST":
        if "delete" in request.POST:
            if not request.user.groupupuser.is_admin_of(group):
                messages.warning("You are not administrator for this group!")
                return redirect("/admin/groups/{0}".format(pk))
            group.group_pic.delete(save=True)
            group.delete()
            return HttpResponseRedirect("/")
        else:
            return redirect("/admin/groups/{0}".format(pk))
    else:
        return render(request, "groupup_admin/delete_user.html", {"group": group})

groupup/groupup/groupup_admin/templates/groupup_admin/admin_index.html
{% extends 'accounts/base.html' %}

{% block title %}Admin site{% endblock %}

{% block content %}
<div class="container mb-4">
  <div class="row">
    <div class="col-md-1 col-xl-1"></div>
    <div class="col-md-10 col-xl-10">
      <h1 style="text-align: center; margin-top: 10px;">Admin site</h1>
      <h2 style="text-align: center; margin-top: 30px; margin-bottom: 40px;">Your groups</h2>
      <div class="d-flex flex-wrap justify-content-around" style="gap: 10px;">
      {% for group in groups %}
        <div class="group-item">
          <a class="text-decoration-none" style="color: inherit;" href="{% block group_links %}{% url 'group_admin:group_browsing' group.id %}{% endblock %}">
          <img class="group-pic-list" src="{{ MEDIA_URL }}{{ group.group_pic.url }}" alt="Group picture for {{ group.name }}">
          <h2>{{ group.name }}</h2>
          <p>{{ group.get_age_gap }}</p>
          <h3>Some Interests</h3>
          <ul class="list-group list-group-horizontal" style="background-color: lightgrey;">
            {% for interest in group.get_three_interests %}
            <li class="list-group-item flex-fill">{{ interest.name }}</li>
            {% endfor %}
          </ul>
          </a>
        </div>
      {% endfor %}
      </div>
      <h3 style="text-align: center; margin-top: 40px; ">Group Browsing</h3>
      <p style="text-align: center; font-size: large;">Find other groups and potential matches <a href="{% url 'group_admin:groups' %}">here</a>!
    </div>
    <div class="col-md-1 col-xl-1"></div>
  </div>
  <div class="row">
    <div class="col-md-1 col-xl-1"></div>
    <div class="col-md-10 col-xl-10">
      <h2 style="text-align: center; margin-top: 10px; margin-bottom: 20px;">Match requests</h2>
      <ul class="d-flex flex-wrap justify-content-center" style="list-style-type: none; padding: 0; gap: 20px;">
        {% for group in groups %}
        <li>
          <a class="btn btn-outline-success" href="{% url 'group_admin:view_match' group.id %}">
            Match requests for {{ group.name }}
          </a>
        </li> 
        {% endfor %}
      </ul>
    </div>
    <div class="col-md-1 col-xl-1"></div>
  </div>
</div>
{% endblock %}

groupup/groupup/groupup_admin/templates/groupup_admin/all_groups.html
{% extends 'accounts/base.html' %}

{% block content %}
<style>
  .checkbox-dropdown {
    width: 200px;
    border: 1px solid #aaa;
    padding: 10px;
    position: relative;
    user-select: none;
  }

  /* Display CSS arrow to the right of the dropdown text */
  .checkbox-dropdown:after {
    content: '';
    height: 0;
    position: absolute;
    width: 0;
    border: 6px solid transparent;
    border-top-color: #000;
    top: 50%;
    right: 10px;
    margin-top: -3px;
  }

  /* Reverse the CSS arrow when the dropdown is active */
  .checkbox-dropdown.is-active:after {
    border-bottom-color: #000;
    border-top-color: #fff;
    margin-top: -9px;
  }

  .checkbox-dropdown-list {
    list-style: none;
    margin: 0;
    padding: 0;
    position: absolute;
    top: 100%;
    /* align the dropdown right below the dropdown text */
    border: inherit;
    border-top: none;
    left: -1px;
    /* align the dropdown to the left */
    right: -1px;
    /* align the dropdown to the right */
    opacity: 0;
    /* hide the dropdown */

    transition: opacity 0.4s ease-in-out;
    max-height: 400px;
    overflow: scroll;
    overflow-x: hidden;
    pointer-events: none;
    /* avoid mouse click events inside the dropdown */
  }

  .is-active .checkbox-dropdown-list {
    opacity: 1;
    /* display the dropdown */
    pointer-events: auto;
    /* make sure that the user still can select checkboxes */
  }

  .checkbox-dropdown-list li label {
    display: block;
    border-bottom: 1px solid silver;
    padding: 10px;
    transition: all 0.2s ease-out;
    background: #fff;
  }

  .checkbox-dropdown-list li label:hover {
    background-color: #555;
    color: white;
  }
</style>

<div class="container mb-4">
  <h1 style="text-align: center; margin-top: 10px;">All Groups</h1>
  <div class="row mb-4">
    <div class="col-md-1 col-xl-1"></div>
    <div class="col-md-10 col-xl-10">
      <div class="checkbox-dropdown">
        Filter on interest
        <ul class="checkbox-dropdown-list">
          {% for interest in interests %}
          <li>
            <label>
              <input type="checkbox" value="{{interest.pk}}" name="{{interest.name}}" />{{ interest.name }}</label>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1 col-xl-1"></div>
    <div class="col-md-10 col-xl-10">
      <div class="d-flex flex-wrap justify-content-between" style="gap: 10px;">
        {% for group in groups %}
        <div class="group-item">
          <a class="text-decoration-none" style="color: inherit;"
            href="{% block group_links %}{% url 'group_admin:group_browsing' group.id %}{% endblock %}">
            <img class="group-pic-list" src="{{ MEDIA_URL }}{{ group.group_pic.url }}"
              alt="Group picture for {{ group.name }}">
            <h2>{{ group.name }}</h2>
            <p>{{ group.get_age_gap }}</p>
            <h3>Some Interests</h3>
            <ul class="list-group list-group-horizontal" style="background-color: lightgrey;">
              {% for interest in group.get_three_interests %}
              <li class="list-group-item flex-fill">{{ interest.name }}</li>
              {% endfor %}
            </ul>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-1 col-xl-1"></div>
  </div>
</div>

<script>
  const searchParams = new URLSearchParams(window.location.search);
  const originalCheckedItems = (searchParams.get("interests") ?? "")
    .split(",")
    .filter(x => x !== "");
  Array.from(document.querySelectorAll(".checkbox-dropdown-list input[type=checkbox]"))
    .forEach(i => i.checked = originalCheckedItems.indexOf(i.value) >= 0);

  document.querySelector(".checkbox-dropdown").addEventListener("click", e => {
    e.stopPropagation();
    e.currentTarget.classList.toggle("is-active");
    const searchParams = new URLSearchParams(window.location.search);
    const checkedItems = Array.from(
      document.querySelectorAll(".checkbox-dropdown-list input[type=checkbox]"))
      .filter(x => x.checked)
    if (checkedItems.length === originalCheckedItems.length) {
      return;
    }
    searchParams.set(
      "interests",
      checkedItems.map(x => x.value).join(","));
    window.location.search = searchParams.toString();
  });
</script>
{% endblock %}

groupup/groupup/groupup_admin/templates/groupup_admin/delete_user.html
{% extends 'accounts/base.html' %}

{% block title %}Delete group site{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2 col-xl-2"></div>
        <div class="col-md-8 col-xl-8">
            <h1 style="text-align: center; margin-bottom: 2em;">Are you sure you want to delete {{ group.name }}</h1>
            <form method="post" style="display: flex; justify-content: center; gap: 1em;">
                {% csrf_token %}
                <button type="submit" name="delete" class="btn btn-danger">Yes, I am sure</button>
                <button type="submit" name="cancel" class="btn btn-success">No, cancel</button>
            </form>
        </div>
        <div class="col-md-2 col-xl-2"></div>
    </div>
</div>
{% endblock %}

groupup/groupup/groupup_admin/templates/groupup_admin/group_site_admin.html
{% extends 'accounts/group_site.html' %}
{% load bootstrap5 %}

{% block title %}Group Site for {{ group.name }}{% endblock %}

{% block admin_content %}
<div class="container" style="margin: 0 2em 2em 2em;">
  {% if group in user.groupupuser.get_groups_where_admin %}
    <a class="btn btn-primary admin-buttons" href="#">Edit group</a>
    <h2 style="margin-top: 40px;">Invite users</h2>
    <form action="{{ group.id }}" method="post" style="max-width: 700px;">
      {% csrf_token %}
      {% bootstrap_form invite_form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary admin-buttons">
          Invite!
        </button>
      {% endbuttons %}
    </form>

  {% else %}
    <div style="display: flex; flex-direction: column; gap: 1rem;">
    {% if group.connected_group.all %}
    <h2 style="margin-top: 40px;">Wanna match?</h2>
    {% for usergroup in user.groupupuser.get_groups_where_admin %}
      {% if group not in usergroup.get_related_groups %}
        <div>
          <a class="btn btn-primary" href="{% url 'group_admin:send_match' usergroup.id %}" style="width: 40%; word-break: break-word;">
          Send match request on behalf of {{ usergroup.name }}
          </a>
        </div>
      {% endif %}
    {% endfor %}
    {% endif %}
    
    {% if group in user.groupupuser.confirmed_groups_where_admin %}
        <h2 style="margin-top: 40px;">Have you met this group?</h2>
    {% endif %}
    {% for usergroup in user.groupupuser.get_groups_where_admin %}
      {% if group in usergroup.get_confirmed_groups %}
      <div>
        <a href="{% url 'group_admin:set_met' usergroup.id %}" class="btn btn-primary" style="width: 40%;">
          {{ usergroup.name }} have met this group
        </a>
      </div>
      {% endif %}
    {% endfor %}
    </div>
  {% endif %}

  {% if group in user.groupupuser.get_groups_where_admin %}
  <h2 style="margin-top: 40px;">Add or remove available dates</h2>
  <form action="{% url 'group_admin:add_date' group.id %}" method="post" style="max-width: 700px;">
    {% csrf_token %}
      {% bootstrap_form add_date %}
      {% buttons %}
        <button type="submit" class="btn btn-primary admin-buttons">
          Add
        </button>
      {% endbuttons %}
      {{ add_date.non_field_errors }}
  </form>
  <form action="{% url 'group_admin:remove_date' group.id %}" method="post" style="max-width: 700px;">
    {% csrf_token %}
      {{ remove_date }}
      {% buttons %}
        <button type="submit" class="btn btn-primary admin-buttons" style="margin: 1em 0;">
          Remove
        </button>
      {% endbuttons %}
  </form>
  <a href="{% url 'group_admin:delete_group' group.id %}" class="btn btn-danger btn-lg" style="margin-top: 40px;">Delete Group</a>
  {% endif %}
  </div>
{% endblock %}

groupup/groupup/groupup_admin/templates/groupup_admin/group_site_handle_request.html
{% extends 'accounts/group_site.html' %}
{% load bootstrap5 %}

{% block invite_user %}{% endblock %}

{% block admin_content %}
<div class="container" style="margin-left: 2em;">
  <h2>Handle match request</h2>
  <form method="post" style="margin-bottom: 1em;">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="OK">
  </form>
</div>
{% endblock %}

groupup/groupup/groupup_admin/templates/groupup_admin/match_requests.html
{% extends 'accounts/base.html' %}

{% block title %}Match requests for {{ groupname }}{% endblock %}


{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; margin-top: .5em;">
  <h1>Match requests for {{ groupname }}</h1>
  <ul style="list-style: none; padding: 0;">
    {% for group in requesting_groups %}
      <li>
        <a href="{% url 'group_admin:handle_request' group.id %}">{{ group.name }} has requested a match</a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

groupup/groupup/groupup_admin/templates/groupup_admin/review.html
{% extends 'accounts/base.html' %}
{% load bootstrap5 %}

{% block title %}Review matched group{% endblock %}

{% block content %}

<div style="display: flex; flex-direction: column; align-items: center;">
    <h2 style="margin-top: 20px;">Write a review</h2>
    <form method="post" style="margin-top: 20px;">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class= "btn btn-primary" type="submit">Submit</button>
    </form>
</div>

{% endblock %}